version: '3.8'

services:
  # Frontend service - development overrides
  frontend:
    build:
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:5000/api
      - VITE_ENV=development
    command: npm run dev

  # Backend service - development overrides
  backend:
    build:
      dockerfile: Dockerfile.backend.dev
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/salespace
      - SECRET_KEY=development_secret_key
      - CORS_ORIGINS=http://localhost:3000
      - DEBUG=True
    command: flask run --host=0.0.0.0 --port=5000