version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - frontend_node_modules:/app/node_modules

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/salespace
      - SECRET_KEY=your_secret_key_here
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - backend_data:/app/data
      - backend_uploads:/app/uploads

  # Database service
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=salespace
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  backend_data:
  backend_uploads:
  frontend_node_modules: